---
- name: Configure self-hosted GitHub runners
  hosts: all
  become: true
  roles:
    - apt_cache
    - common
    - trivy
    - docker
    - docker_registry_mirror
    - gha_cache
    - github_runner
